services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: imagen-saberes:latest
    container_name: saberes-container
    ports:
      - "8081:3000"
    env_file:
      - .env
    depends_on: []
    restart: unless-stopped
